using BackendApi.Enums;

namespace BackendApi.ErrorHandling;

/// <summary>
/// BusinessException are generated by the API services.
/// They can be returned by controllers in results objects.
/// </summary>
public class BusinessException : Exception
{
    public BusinessError Error { get; private set; }

    public BusinessException() { }

    public BusinessException(string message) : base(message) { }

    public BusinessException(string message, Exception inner) : base(message, inner) { }

    public BusinessException(ErrorCode code, string message, Exception inner = null) : base(message, inner)
    {
        Error = new BusinessError(code, message, inner);
    }

    public override string ToString()
    {
        return $"BusinessException: {Error}";
    }
}